---
ssh_port: 22
ssh_log_level: "VERBOSE"
ssh_permit_root: "no"
ssh_grace_time: 30
ssh_max_auth_tries: 3
ssh_max_sessions: 2
ssh_listen_address: "0.0.0.0"
ssh_pubkey_auth: "yes"
ssh_host_auth: "no"
ssh_ignore_rhosts: "yes"
ssh_password_auth: "no"
ssh_empty_password: "no"
ssh_auth_methods: "publickey"
ssh_authorized_keys_file: ".ssh/authorized_keys"
ssh_challenge_response_auth: "no"
ssh_use_pam: "yes"
ssh_x11_forwarding: "no"
ssh_print_motd: "no"
ssh_print_last_log: "yes"
ssh_client_alive_int: 1800
ssh_client_alive_max: 0
