---
k3s_version: v1.25.9+k3s1

ansible_user: ansible
systemd_dir: /etc/systemd/system

system_timezone: "America/Denver"

flannel_iface: "eth0"

apiserver_endpoint: "10.19.49.70"

k3s_token: "{{ lookup('hashi_vault', 'secret=kv/data/k3s:k3s_token') }}"

k3s_node_ip: '{{ ansible_facts[flannel_iface]["ipv4"]["address"] }}'

k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

extra_args: >-
  --flannel-iface={{ flannel_iface }}
  --node-ip={{ k3s_node_ip }}

extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik
extra_agent_args: >-
  {{ extra_args }}

kube_vip_tag_version: "v0.5.12"

metal_lb_type: "native"
metal_lb_mode: "layer2"

metal_lb_frr_tag_version: "v7.5.1"
metal_lb_speaker_tag_version: "v0.13.9"
metal_lb_controller_tag_version: "v0.13.9"

metal_lb_ip_range: "10.19.49.71-10.19.49.89"